config/routes.rb
Voterama::Application.routes.draw do

  root to: 'ideas#index'
  resources :ideas, only: [:new, :create, :index]

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
  end

  def new
    @idea = Idea.new
  end

  def create
    # TODO: send flash with redirect - wierdness
    @idea = Idea.new(idea_params)

    if @idea.save
      flash[:notice] = "Idea synchronized"
      redirect_to ideas_path
    else
      render :new
    end
  end

  def idea_params
    params.require(:idea).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ideas/index.slim
h1 The Best Ideas In The World

div
  = link_to "New Idea", new_idea_path

- @ideas.each do |idea|
  div
    h3= idea.title
    p= idea.description

app/views/ideas/new.html.slim
div#flash-message
  = flash[:notice]

= form_for @idea do |f|
  = f.label :title
  = f.text_field :title
  = f.label :description
  = f.text_area :description
  = f.submit "Upload to the Matrix"

app/views/ideas/new.slim
= form_for @idea do |f|
  = f.label :title
  = f.text_field :title
  = f.label :description
  = f.text_area :description
  = f.submit "Upload to the Matrix"

app/views/layouts/_flash.slim
div#flash-message
  = flash[:notice]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: 'layouts/flash' %>
    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>